# Site settings
title: "Junteng Liu"
email: "jliugi@connect.ust.hk"
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage of Junteng Liu
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: junteng88716710
github_username:  Vicent0205
google_scholar: tbK9jl4AAAAJ

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Author settings
author:
  name: "Junteng Liu"
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  twitter: "junteng88716710"
  google_scholar: "tbK9jl4AAAAJ"